import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen overflow-hidden ">
          <div className="flex m-5 flex-col items-center justify-center gap-2 ">
            <div></div>
            <input
              type="text"
              placeholder="Enter your answer here"
              className="input rounded p-1 input-bordered w-full max-w-xs text-black"
            />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
